### ISSUE TITLE
draw subinstance not working

### ISSUE THREAD

**Issue by zswgzx** [pyxnat/pyxnat#102]
Just curious how it would look as suggested from Advanced tutorial:

.../pyxnat/core/help.py", line 505, in experiments
    self._draw_rest_resource(graph, save=None)
.../pyxnat/core/help.py", line 521, in _draw_rest_resource
    pos = nx.graphviz_layout(graph, prog='twopi', args='')
AttributeError: module 'networkx' has no attribute 'graphviz_layout'

**Comment by jhuguetn** [comment]
The package structure has changed in recent versions of `networkx`, I will create a PR including a fix for this behaviour since that's clearly an error in the code.

FYI, function `graphviz_layout()` should be used as follows:
```
pos = nx.drawing.nx_agraph.graphviz_layout(graph, prog='twopi', args='')
```
