### ISSUE TITLE
Add a lint check in Travis

### ISSUE THREAD

**Issue by ayan-b** [pyxnat/pyxnat#126]
A lint check job can be added to Travis using flake8.

**Comment by ayan-b** [comment]
I would like to work on this issue.

**Comment by jhuguetn** [comment]
Hi @ayan-b, 
Cool with it, go ahead and create a PR with your proposal.  

BTW, note that we have a [GSoC'20 project](https://neurostars.org/t/gsoc-2020-project-idea-18-pyxnat-enhanced-interfacing-with-a-neuroimaging-data-management-platform-in-python/5756) proposal open that you might be interested in applying for.
