### ISSUE TITLE
is it possible to push data to prearchive ?

### ISSUE THREAD

**Issue by alexpron** [pyxnat/pyxnat#152]
Hello pyxnaters, thank you for your work on pyxnat. 
I am using pyxnat to automatically load thousands of DICOM data to an XNAT server. I sometimes end up with some corrupted scans (and  DICOM ressources)  whereas original DICOM data are not corrupted . Ressources and associated Xnat entities created can not be deleted either by pyxnat or XNAT graphical interface (error 500 load ressource). 
Hence, I would like to know if it is possible to push data into XNAT prearchive using pyxnat.
Thank you in advance,
Alex

**Comment by xgrg** [comment]
Hi Alex,
Just to make sure that I understand your question: would the following post be of any use to you?
http://xgrg.github.io/pushing-bulk-legacy-data-to-XNAT/

It does not use **pyxnat** *per se*; still it shows an efficient (and scriptable) way to push data into XNAT prearchive.
Does it help?

**Comment by jhuguetn** [comment]
Alternatively, if using DICOM communications protocol **is not** an option, you could try doing as follows,

(Note that I am transferring a previously zipped directory containing a set of DICOM files)

```python
import pyxnat

c = pyxnat.Interface(config='.xnat.cfg')

uri = '/data/services/import'
options = {'PROJECT_ID':'my_sandbox',
           'SUBJECT_ID':'my_subject',
           'EXPT_LABEL':'my_subject_mr01',
           'import-handler':'DICOM-zip',
           'prearchive':'true',
           'inbody':'true'}
hdrs = {'Content-Type': 'application/octet-stream'}
imgs_file = '/tmp/pyxnat/DICOM.zip'

with open(imgs_file, 'rb') as f:
    resp = c.post(uri, headers=hdrs, data=f, params=options)
resp.raise_for_status()
```
More info on options used/available [here](https://wiki.xnat.org/display/XAPI/Image+Session+Import+Service+API).

**Comment by xgrg** [comment]
Alright then. Feel free to share some feedback on this as it might be a potentially useful addition for a future release.
