### ISSUE TITLE
Receiving empty list, not list of projects

### ISSUE THREAD

**Issue by andersonwinkler** [pyxnat/pyxnat#162]
Dear all,

First time using pyxnat, not being able to make it work... what am I doing wrong?

```
import pyxnat
central = pyxnat.Interface(server="https://myserver.com",
                        user='myusername',
                        password='mypassword')
my_projects = central.select.projects().get()
```

This returns an empty list, yet the web interface shows me 6 different projects.

What should I have done differently?

Thanks!

Anderson

**Comment by xgrg** [comment]
Typically a wrong login/password will give this behavior.

**Comment by andersonwinkler** [comment]
Thank you. Both login and password are correct.

But indeed, if I purposefully enter them wrongly, the result is the same. No error message indicating that authentication failed.

How to check if auth was successful?

**Comment by jhuguetn** [comment]
@andersonwinkler, could you try the following and see what response you get?

```
central.head('/')
```

If `pyxnat` connection worked properly, the above request will return a HTTP response status code #200 (OK). If there's something wrong in the client side with the passed credentials or the server URL you'll then get a #401 status code (unauthorized).

**Comment by andersonwinkler** [comment]
Thank you. This gave 401.

I went to the web interface and changed my password; there was a "$" in it; I replaced it for a new one that has instead "@" as special character and tried again. Now I get 200.

I can't believe this would be the issue but the web interface doesn't say what special characters are allowed. An "_" for example doesn't seem to count as special.

In any case, it seems to be working now, and I receive a list populated with the correct project numbers. All good!

Thanks!

Anderson

**Comment by scandel** [comment]
I know this is an old issue and that it's closed, but I ran into the same problem, with a different cause. So I write it here in case it helps others. 

I tried: 
```python
>>> from pyxnat import Interface
>>> myxnat = Interface(server="https://myxnat.org", user="myuser", password="p@ssw0rd")
>>> myxnat.select.projects().get()
[]
```
I also got an empty list of projects, whereas the user and password are valid and contain no special characters. 

The `myxnat.head("/")`command gave an error involving SSL certificates ; so I set the `verify` parameter to `False`, because the certificate is self-signed on the XNAT instance I use, and it solved the connection issue: 
```python
>>> myxnat = Interface(server="https://myxnat.org", user="myuser", password="p@ssw0rd", verify=False)
>>> myxnat.select.projects().get()
['PROJECT1', 'PROJECT2',...]
```
