### ISSUE TITLE
nosetests deprecation in Debian

### ISSUE THREAD

**Issue by emollier** [pyxnat/pyxnat#166]
Greetings,

For information, the Debian project intends to sunset nosetests, as it is unmaintained for several years, and replaced by other test engines such as pytest.  As such, the pyxnat package is affected by [Debian Bug #1018603].  I thought you might want to be aware of the issue.

For what it's worth, I wrapped up a [patch to fix/workaround the issue], but it depends on some previous distribution specific modifications.  In any case you might be interested of its existence.  I haven't patched all the occurrences of nosetest projects and users to replace by pytest, or some naming more generic though, to keep the change simple enough.

[Debian Bug #1018603]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018603
[patch to fix/workaround the issue]: https://salsa.debian.org/med-team/pyxnat/-/blob/master/debian/patches/pytest.patch

Have a nice day,  :)
Étienne.

**Comment by jhuguetn** [comment]
We internally discussed switching to a more actively maintained testing framework some time ago, this might be the push we needed to do so ;) 

Thanks a lot for the heads-up, @emollier.

**Comment by jhuguetn** [comment]
Hi @emollier, note that https://github.com/pyxnat/pyxnat/pull/167 fixes the reported issue with nose (has been replaced by pytest). Thanks

**Comment by emollier** [comment]
Hi Jordi,

Great, we'll be able to drop our patch on your next pyxnat
release.  Thanks for your time on the move to pytest!

Have a nice day,  :)
-- 
Étienne Mollier ***@***.***>
Fingerprint:  8f91 b227 c7d6 f2b1 948c  8236 793c f67e 8f0d 11da
Sent from /dev/tty1, please excuse my verbosity.
On air: Saga - Shake That Tree

**Comment by jhuguetn** [comment]
Closing the issue, see https://github.com/pyxnat/pyxnat/releases/tag/1.6. Thanks @emollier.
