### ISSUE TITLE
`save_config` fails when location is in the working directory

### ISSUE THREAD

**Issue by Pkaps25** [pyxnat/pyxnat#180]
When saving the config file for an interface, the `save_config` method will raise an error if the location provided is a relative path in the current directory. This can be fixed by checking that the directory name of the config file is not the empty string.

Error trace:
```
>>> central.save_config("central.cfg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/dicom-exper-H58PIbO7-py3.11/lib/python3.11/site-packages/pyxnat/core/interfaces.py", line 437, in save_config
    os.makedirs(os.path.dirname(location))
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by jhuguetn** [comment]
Thanks @Pkaps25 for reporting the issue. Setting the config. file path via `os.path.abspath()` method will do the trick. We will work on that. By the way, we could probably also include a `os.path.expanduser()` for expanding user's home directory.

**Comment by Pkaps25** [comment]
Thanks for the response! I'm happy to put up a fix for this as well.

**Comment by jhuguetn** [comment]
As you wish, feel free to contribute creating a new PR then.
