### ISSUE TITLE
USER.ID Not being populated on project. 

### ISSUE THREAD

**Issue by gkowalski** [pyxnat/pyxnat#188]
Running this code : 

import xnat
XNAT_USERID = os.environ.get("XNAT_USERID")
XNAT_PASSWORD = os.environ.get("XNAT_PASSWORD")
XNAT_SITE = os.environ.get("XNAT_SITE")
with xnat.connect( server=XNAT_SITE, password=XNAT_PASSWORD, user=XNAT_USERID) as session:

 for user in session.users.values():
print( f"User = {user} ")
print( f"User email = {user.email} ")
print( f"XNAT id = {[user.id](http://user.id/)} ")  

Prints the [user.id](http://user.id/) for each user 

But this code returns "None" for the [user.id](http://user.id/) , but the email VALUE comes thru : 

import xnat
XNAT_USERID = os.environ.get("XNAT_USERID")
XNAT_PASSWORD = os.environ.get("XNAT_PASSWORD")
XNAT_SITE = os.environ.get("XNAT_SITE")
with xnat.connect( server=XNAT_SITE, password=XNAT_PASSWORD, user=XNAT_USERID) as session:

myproject = session.projects['IDSC1077']

for user in myproject.users.values():
print( f"User = {user} ")
print( f"User email = {user.email} ")
print( f"XNAT id = {[user.id](http://user.id/)} ") # EMPTY WHEN QUerying on project

**Comment by jhuguetn** [comment]
Hi @gkowalski, 

I suspect your code uses `xnatpy` and not `pyxnat` so there's not much we can do. Nevertheless, you can easily do as follows working with pyxnat if you want to:
```
import pyxnat
with pyxnat.Interface( server=XNAT_SITE, password=XNAT_PASSWORD, user=XNAT_USERID) as session:
    print([(usr, session.manage.users.id(usr), session.manage.users.email(usr)) for usr in session.manage.users()])
```

And at project level (split by user role),
```
import pyxnat
with pyxnat.Interface( server=XNAT_SITE, password=XNAT_PASSWORD, user=XNAT_USERID) as session:
    myproject = session.select.project('IDSC1077')
    print([(usr, session.manage.users.id(usr), session.manage.users.email(usr)) for usr in myproject.owners()])
    print([(usr, session.manage.users.id(usr), session.manage.users.email(usr)) for usr in myproject.members()])
    print([(usr, session.manage.users.id(usr), session.manage.users.email(usr)) for usr in myproject.collaborators()])
```
