### ISSUE TITLE
nosetests xnat central password expired

### ISSUE THREAD

**Issue by koekie** [pyxnat/pyxnat#59]
I tried to run the tests of pyxnat, but the password of the nosetests user on xnat central was expired. I tried to set it to the same password but xnat central doesn't permit this.
Next step was to try and set another password and then change back, of course this isn't permitted either ;)

So, long story short: the new password is "nose".

Maybe you can get one of the xnat central admins to set the password back to the original one and make sure the password for this account cannot expire?

Sorry for any inconvenience!

**Comment by DavidJJ** [comment]
Having updated password is reasonable. The password probably should be updated on a semi-regular basis. closing ticket.
