### ISSUE TITLE
Concurrent access results in XNAT write failure

### ISSUE THREAD

**Issue by FredLoney** [pyxnat/pyxnat#61]
When an imaging pipeline involving many pyxnat write operations is deployed to a cluster environment, the execution fails sporadically in one of several XNAT access tasks app. 80% into the 2-day pipeline. There is no useful error message, simply an indication of which task failed. The problem defies isolation or reproduction. The cause might be due to  a concurrency conflict, possibly arising from one of the following causes:
- the pyxnat config file specifies a temp directory that _is not_ shared by all concurrent jobs,  resulting in inconsistent cache content
- the pyxnat config file specifies a temp directory that _is_ shared by some concurrent jobs, resulting in unsynchronized pyxnat write conflicts across jobs
- the non-reentrant pyxnat's custom non-http2lib cache is corrupted
-  an XNAT archive directory access race condition

The work-around is to serialize pipeline XNAT to a single node at a time.

Are the above causes plausible?

Is there a best practice for running pyxnat concurrently?

**Comment by aharding** [comment]
Based on my experience, I suspect (2) and therefore not (1), assume (3) is omnipresent, and have no particular reason to suspect (4). Programming very defensively around pyxnat's current cache implementation seems mostly effective for me, along with heeding the environment's I/O constraints. The following is a bit ad-hoc and constitutes "defensive" if not generally "best" practice.

When I run jobs using pyxnat in a cluster/batch environment, I am [at least so far] conservative and perform only the *read* operations as batch processes, then aggregate and review (and re-run if needed) before serially uploading results. (Todo: improve automation here.) Specifically:

I [not entirely superstitiously] anticipate trouble with the cache: each job (and/or read operation, depending on how the batch is subdivided into jobs) gets its own distinct cachedir. (I also prefer to rely as much as possible on node-local storage to avoid network filesystem load/latency, but you tailor that to your own environment and staging practices.)

When I last checked, pyxnat's configfile takes precedence over the parameter values supplied to the Interface constructor, so you can either create and pass a configfile for every job (varying only this single parameter) or parse the One True configfile yourself and pass the parms to the Interface (monkeypatch or whatever), each time substituting the current job's cachedir. I've gone with the latter in the past; something like this:

`conf = json.load( open(configFile,'rb') )`
`# Receive/concoct pathToUniqueCache, check access, whatever you require`
`ifc = Interface( user=str(conf['user']),...,cachedir=pathToUniqueCache)`

Do whatever input validation & munging you want, leave it up to the caller to prepare pathToUniqueCache, etc.

Remaining XNAT I/O problems seem related to hung processes begat by spamming it to excess using too much simultaneous compute, and handling that gracefully seems beyond the scope of a REST wrapper (especially when there are more basic problems..).

**Comment by DavidJJ** [comment]
With pyXNAT 1.0 the custom caching is gone so you might have better luck with it.  If the problem still persists I can look into it further.
