### ISSUE TITLE
Sphinx documentation:  support Sphinx > 1.2b3

### ISSUE THREAD

**Issue by DavidJJ** [pyxnat/pyxnat#62]
The problem isn't actually with distutils. The problem is with sphinx.  the newest version of Sphinx errors out when using the version of autosummary built into the pyxnat code base.

using Sphinx version 1.2b3 allow the build to succeed.

~~When attempting to distribute pyxnat 9.5.4 to pypi i discovered that python 2.7 no longer supports distutils which is used by pyxnat to build and ship to pypi.
distutils should be replace by setuptools. 
other projects have had the same growing pain:~~
https://github.com/taoliu/MACS/issues/49

**Comment by xgrg** [comment]
Fixed when porting `pyxnat` to Python 3.
