### ISSUE TITLE
Issue with resource.file(myfile).get() if myfile is in a sub-directory

### ISSUE THREAD

**Issue by ghammad** [pyxnat/pyxnat#66]
Dear pyxnat,

I try to download resource files for a given subject/experiment as follows:
1. I make a list of all the available files: files = interface.project(WW).subject(XX).experiment(YY).resource(ZZ).files().get()
2. Then I use this list of file names to actually get the files:
for filename in files:
    interface.project(WW).subject(XX).experiment(YY).resource(ZZ).file(filename).get(pathtowhatever/filename)

The problem is that some files are located in a subdirectory at the resources/resource_label level and thus the request to get the file crashes:
pyxnat.core.errors.DataError: Cannot get file: does not exists

Is there a way round?

Thank you in advance for your help.

Regards

**Comment by DavidJJ** [comment]
The workaround is to use the full path of the file within the resource to retrieve it:

```
resource = interface.project(WW).subject(XX).experiment(YY).resource(ZZ)
file = resource.file('/deep/path/to/file.txt).get('/download/file_txt/to/here.txt')
```

**Comment by loj** [comment]
I have the same problem as described above. Is there a way to programatically discover the full file paths?

**Comment by xgrg** [comment]
Hi @loj,
The behavior you are experiencing is specific to the `get` function, which returns the last part of each element's URI in a `CObject` collection.
To reveal the full path of each file it may be better to iterate through the files using a `for` loop.

```
# Select the right resource and files
p = interface.select.project('your_project')
s = p.subject('your_subject')
e = s.experiment('your_experiment')
files = e.resource('your_resource').files()

# Iterate through files
for f in files:
    uri = f._uri
    label = f.label()
    print('full URI: %s - label: %s'%(uri, label))
```
Does it help?

**Comment by loj** [comment]
Thanks @xgrg! This helps a lot. :-)
