### ISSUE TITLE
scan attribute not being set

### ISSUE THREAD

**Issue by elijahrockers** [pyxnat/pyxnat#70]
petScanData/parameters/startTime refuses to be set.

`scan.attrs.mset(attr_dict)` works if we remove the `startTime` entry, but `mset()` fails completely if `startTime` is present.

How can I best troubleshoot this?

**Comment by DavidJJ** [comment]
This is not a pyxnat problem.  It is a deficiency with XNAT's rest API such that unrecognized attributes cause a mset to fail, while not reporting anything useful back.  If you look carefully you'll find that some of the attributes were set (those listed prior to startTime. 

Your question is better asked on the xnat user group: https://groups.google.com/forum/#!forum/xnat_discussion

but depending on your version of XNAT  the startTime parameter may or may not exist.   I believe startTime came to be in xnat 1.6  prior to that it was called scanTime

see: https://wiki.xnat.org/display/XNAT16/XNAT+1.6+Release+Notes
