### ISSUE TITLE
Python3 Conversion

### ISSUE THREAD

**Issue by jdkent** [pyxnat/pyxnat#75]
Are there any plans making pyxnat python3 compatible in the future? I don't have time in the near future to help with it, but I was curious if this was on the roadmap for pyxnat.

**Comment by johnflavin** [comment]
There isn't really any roadmap for pyxnat. What happens in the future is up to the community. If you or anyone else wants to take on the task of adapting the code for python 3, I don't see a reason it wouldn't be merged in.

**Comment by jimklo** [comment]
I'm in the process of upgrading our project (which uses pyxnat) to Python3.  I might be able to help out here depending upon how extensive this is.  I've already found one issue (it doesn't install correctly under 3.6 -- reports the wrong version number)

**Comment by fepegar** [comment]
Hi all,

Let me know if I can help with that.

**Comment by fepegar** [comment]
Got this error:
```python-traceback
In [6]: from pyxnat import Interface                                                                                                                    

In [7]: central = Interface()                                                                                                                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-1f5b0fa3f222> in <module>
----> 1 central = Interface()

~/git/pyxnat/pyxnat/core/interfaces.py in __init__(self, server, user, password, cachedir, config, anonymous, proxy, verify)
    213 
    214         if self._interactive:
--> 215             self._get_entry_point()
    216 
    217         self.inspect()

~/git/pyxnat/pyxnat/core/interfaces.py in _get_entry_point(self)
    252             except Exception as e:
    253                 if not '/data/JSESSION' in str(e):
--> 254                     raise e
    255 
    256         return self._entry

~/git/pyxnat/pyxnat/core/interfaces.py in _get_entry_point(self)
    245             self._entry = '/REST'
    246             try:
--> 247                 self._jsession = 'JSESSIONID=' + self._exec('/data/JSESSION', force_preemptive_auth=True)
    248                 self._entry = '/data'
    249 

~/git/pyxnat/pyxnat/core/interfaces.py in _exec(self, uri, method, body, headers, force_preemptive_auth, **kwargs)
    353             return
    354 
--> 355         if (response is not None and not response.ok) or is_xnat_error(response.content):
    356             if DEBUG:
    357                 print((list(response.keys())))

~/git/pyxnat/pyxnat/core/errors.py in is_xnat_error(message)
      9 
     10 def is_xnat_error(message):
---> 11     return message.startswith('<!DOCTYPE') or message.startswith('<html>')
     12 
     13 

TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by rgllm** [comment]
@fepegar I forgot to push the last commit, sorry. I will do it as soon as possible.

**Comment by xgrg** [comment]
Hi guys,

there is a pending PR https://github.com/pyxnat/pyxnat/pull/87 to make pyxnat Python3-compatible.
You are welcome to give it a look.

As explained in the discussion, CI tests are failing at the moment but they are successfully passing on the forked version.

**Comment by xgrg** [comment]
Hi guys,

whenever you have time could you please give a look to the recent changes related to pyxnat Python3-compatibility, so that we may update the status of this issue.
Thank you in advance.
