### ISSUE TITLE
Inspect class structure method not working?

### ISSUE THREAD

**Issue by zswgzx** [pyxnat/pyxnat#99]
Using pyxnat 1.1.0.2 with python3.7 in anaconda on Ubuntu 16.04 LTS , when it is connected to a test xnat server, the output of [my_xnatServer].inspect.structure() gives the following error:

.../pyxnat/core/help.py", line 310, in structure
    print('- %s') % 'PROJECTS'
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'

Any suggestion? This may also help me to understand the rest hierarchy better. Thanks in advance!

**Comment by jhuguetn** [comment]
That's clearly an error in the code, should be as follows:
```
print('- %s' % 'PROJECTS')
```

**Comment by zswgzx** [comment]
please elaborate, new to python3...

**Comment by zswgzx** [comment]
how do i update pyxnat after the change, pip install pyxnat?

**Comment by zswgzx** [comment]
Already manually modified as you fixed it, and works well. Thanks jhuguetn!
